---
version: '2'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - PATH=/app/assets/node_modules/.bin:$PATH
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./client:/app
    command: bash -c "cd app && elm-reactor --address=0.0.0.0 --port=8000"
  db:
    image: postgres:9

